import mongoose from 'mongoose';
import dotenv from 'dotenv';
import process from 'node:process';
import Product from '../model/Product.js';

dotenv.config();

const MONGODB_URI =
  process.env.MONGO_URI ||
  process.env.MONGODB_URI ||
  'mongodb://localhost:27017/sweetslice';

const seedData = [
  {
    name: 'Chocolate Delight Cake',
    category: 'Chocolate',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=Chocolate+Delight',
    description: 'Rich chocolate cake with creamy frosting and chocolate chips',
    rating: 4.8,
    inStock: true,
    quantity: 50,
  },
  {
    name: 'Vanilla Dream',
    category: 'Vanilla',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=Vanilla+Dream',
    description: 'Classic vanilla cake with vanilla buttercream frosting',
    rating: 4.6,
    inStock: true,
    quantity: 45,
  },
  {
    name: 'Strawberry Cheesecake',
    category: 'Cheesecake',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Strawberry+Cheesecake',
    description: 'NY style cheesecake with fresh strawberry topping',
    rating: 4.9,
    inStock: true,
    quantity: 30,
  },
  {
    name: 'Black Forest Cake',
    category: 'Chocolate',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Black+Forest',
    description: 'Traditional Black Forest with cherries and whipped cream',
    rating: 4.7,
    inStock: true,
    quantity: 25,
  },
  {
    name: 'Red Velvet Delight',
    category: 'Special',
    price: 549,
    image: 'https://via.placeholder.com/300x300?text=Red+Velvet',
    description: 'Elegant red velvet cake with cream cheese frosting',
    rating: 4.8,
    inStock: true,
    quantity: 35,
  },
  {
    name: 'Lemon Zest Cake',
    category: 'Vanilla',
    price: 449,
    image: 'https://via.placeholder.com/300x300?text=Lemon+Zest',
    description: 'Fresh lemon cake with zesty lemon frosting',
    rating: 4.5,
    inStock: true,
    quantity: 40,
  },
  {
    name: 'Carrot Cake Surprise',
    category: 'Special',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=Carrot+Cake',
    description: 'Moist carrot cake with cream cheese frosting and walnuts',
    rating: 4.6,
    inStock: true,
    quantity: 32,
  },
  {
    name: 'Tres Leches',
    category: 'Special',
    price: 549,
    image: 'https://via.placeholder.com/300x300?text=Tres+Leches',
    description: 'Traditional Latin American three milk cake',
    rating: 4.7,
    inStock: true,
    quantity: 28,
  },
  {
    name: 'Marble Chocolate Cake',
    category: 'Chocolate',
    price: 549,
    image: 'https://via.placeholder.com/300x300?text=Marble+Cake',
    description: 'Swirled chocolate and vanilla cake with chocolate ganache',
    rating: 4.8,
    inStock: true,
    quantity: 38,
  },
  {
    name: 'White Chocolate Mousse',
    category: 'Cheesecake',
    price: 629,
    image: 'https://via.placeholder.com/300x300?text=White+Chocolate',
    description: 'Silky white chocolate mousse with berries',
    rating: 4.9,
    inStock: true,
    quantity: 20,
  },
  {
    name: 'Tiramisu Cake',
    category: 'Cheesecake',
    price: 579,
    image: 'https://via.placeholder.com/300x300?text=Tiramisu',
    description: 'Italian inspired tiramisu cake with mascarpone cream',
    rating: 4.8,
    inStock: true,
    quantity: 25,
  },
  {
    name: 'Chocolate Swiss Roll',
    category: 'Chocolate',
    price: 399,
    image: 'https://via.placeholder.com/300x300?text=Swiss+Roll',
    description: 'Rolled chocolate sponge cake with chocolate cream',
    rating: 4.6,
    inStock: true,
    quantity: 50,
  },
  {
    name: 'Blueberry Cheesecake',
    category: 'Cheesecake',
    price: 599,
    image: 'https://via.placeholder.com/300x300?text=Blueberry',
    description: 'Creamy cheesecake with fresh blueberry compote',
    rating: 4.8,
    inStock: true,
    quantity: 22,
  },
  {
    name: 'Pistachio Dream',
    category: 'Special',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Pistachio',
    description: 'Premium pistachio cake with pistachio buttercream',
    rating: 4.9,
    inStock: true,
    quantity: 15,
  },
  {
    name: 'Coconut Paradise',
    category: 'Vanilla',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=Coconut',
    description: 'Tropical coconut cake with coconut frosting',
    rating: 4.7,
    inStock: true,
    quantity: 35,
  },
  {
    name: 'Matcha Green Tea Cake',
    category: 'Special',
    price: 579,
    image: 'https://via.placeholder.com/300x300?text=Matcha',
    description: 'Premium matcha green tea cake with white chocolate',
    rating: 4.8,
    inStock: true,
    quantity: 18,
  },
  {
    name: 'Chocolate Mousse Cake',
    category: 'Chocolate',
    price: 629,
    image: 'https://via.placeholder.com/300x300?text=Mousse',
    description: 'Light chocolate mousse on chocolate cake base',
    rating: 4.9,
    inStock: true,
    quantity: 24,
  },
  {
    name: 'Raspberry Dream Cake',
    category: 'Vanilla',
    price: 549,
    image: 'https://via.placeholder.com/300x300?text=Raspberry',
    description: 'Vanilla cake with fresh raspberries and raspberry mousse',
    rating: 4.7,
    inStock: true,
    quantity: 28,
  },
  {
    name: 'Cappuccino Cake',
    category: 'Special',
    price: 529,
    image: 'https://via.placeholder.com/300x300?text=Cappuccino',
    description: 'Coffee flavored cake with cappuccino frosting',
    rating: 4.6,
    inStock: true,
    quantity: 30,
  },
  {
    name: 'Candy Paradise Cake',
    category: 'Special',
    price: 649,
    image: 'https://via.placeholder.com/300x300?text=Candy+Paradise',
    description: 'Festive cake decorated with colorful candies and sprinkles',
    rating: 4.8,
    inStock: true,
    quantity: 20,
  },
  {
    name: 'Midnight Fudge Cake',
    category: 'Chocolate',
    price: 679,
    image: 'https://via.placeholder.com/300x300?text=Midnight+Fudge',
    description: 'Dark chocolate cake with ganache and chocolate curls',
    rating: 4.9,
    inStock: true,
    quantity: 26,
  },
  {
    name: 'Double Choco Crunch',
    category: 'Chocolate',
    price: 629,
    image: 'https://via.placeholder.com/300x300?text=Double+Choco+Crunch',
    description: 'Crunchy chocolate praline layered with soft sponge',
    rating: 4.8,
    inStock: true,
    quantity: 29,
  },
  {
    name: 'Silky Vanilla Bloom',
    category: 'Vanilla',
    price: 469,
    image: 'https://via.placeholder.com/300x300?text=Vanilla+Bloom',
    description: 'Classic vanilla sponge with silky whipped vanilla cream',
    rating: 4.7,
    inStock: true,
    quantity: 42,
  },
  {
    name: 'Honey Almond Vanilla Cake',
    category: 'Vanilla',
    price: 519,
    image: 'https://via.placeholder.com/300x300?text=Honey+Almond+Vanilla',
    description: 'Vanilla almond cake sweetened with floral honey glaze',
    rating: 4.6,
    inStock: true,
    quantity: 34,
  },
  {
    name: 'Caramel Cheesecake',
    category: 'Cheesecake',
    price: 629,
    image: 'https://via.placeholder.com/300x300?text=Caramel+Cheesecake',
    description: 'Creamy baked cheesecake with salted caramel drizzle',
    rating: 4.8,
    inStock: true,
    quantity: 27,
  },
  {
    name: 'Biscoff Cheesecake',
    category: 'Cheesecake',
    price: 649,
    image: 'https://via.placeholder.com/300x300?text=Biscoff+Cheesecake',
    description: 'Velvety cheesecake with caramelized biscuit topping',
    rating: 4.9,
    inStock: true,
    quantity: 23,
  },
  {
    name: 'Kesar Pista Celebration Cake',
    category: 'Special',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Kesar+Pista',
    description: 'Indian festive cake infused with saffron and pistachio',
    rating: 4.8,
    inStock: true,
    quantity: 18,
  },
  {
    name: 'Rose Milk Fusion Cake',
    category: 'Special',
    price: 579,
    image: 'https://via.placeholder.com/300x300?text=Rose+Milk+Cake',
    description: 'Soft sponge soaked with rose milk and topped with petals',
    rating: 4.7,
    inStock: true,
    quantity: 24,
  },
  {
    name: 'Mini Birthday Sprinkle Cake',
    category: 'Birthday Cakes',
    price: 429,
    image: 'https://via.placeholder.com/300x300?text=Birthday+Sprinkle',
    description: 'Birthday favorite loaded with rainbow sprinkles',
    rating: 4.7,
    inStock: true,
    quantity: 33,
  },
  {
    name: 'Confetti Party Cake',
    category: 'Birthday Cakes',
    price: 499,
    image: 'https://via.placeholder.com/300x300?text=Confetti+Party',
    description: 'Funfetti sponge with creamy frosting for celebrations',
    rating: 4.8,
    inStock: true,
    quantity: 31,
  },
  {
    name: 'Pink Velvet Birthday Cake',
    category: 'Birthday Cakes',
    price: 559,
    image: 'https://via.placeholder.com/300x300?text=Pink+Velvet+Birthday',
    description: 'Pink velvet sponge with smooth cream cheese frosting',
    rating: 4.8,
    inStock: true,
    quantity: 28,
  },
  {
    name: 'Classic Tier Wedding Cake',
    category: 'Wedding Cakes',
    price: 1599,
    image: 'https://via.placeholder.com/300x300?text=Classic+Tier+Wedding',
    description: 'Traditional three-tier white wedding centerpiece cake',
    rating: 5.0,
    inStock: true,
    quantity: 10,
  },
  {
    name: 'Floral Arch Wedding Cake',
    category: 'Wedding Cakes',
    price: 1899,
    image: 'https://via.placeholder.com/300x300?text=Floral+Arch+Wedding',
    description: 'Elegant wedding cake with handcrafted floral arch design',
    rating: 5.0,
    inStock: true,
    quantity: 8,
  },
  {
    name: 'Lavender Pearl Wedding Cake',
    category: 'Wedding Cakes',
    price: 1999,
    image: 'https://via.placeholder.com/300x300?text=Lavender+Pearl+Wedding',
    description: 'Premium lavender-toned wedding cake with pearl finish',
    rating: 4.9,
    inStock: true,
    quantity: 6,
  },
  {
    name: 'Belgian Truffle Specialty Cake',
    category: 'Specialty Cakes',
    price: 699,
    image: 'https://via.placeholder.com/300x300?text=Belgian+Truffle+Specialty',
    description: 'Rich specialty truffle cake made with Belgian couverture',
    rating: 4.9,
    inStock: true,
    quantity: 22,
  },
  {
    name: 'Mango Mousse Specialty Cake',
    category: 'Specialty Cakes',
    price: 619,
    image: 'https://via.placeholder.com/300x300?text=Mango+Mousse+Specialty',
    description: 'Light mango mousse cake finished with tropical glaze',
    rating: 4.7,
    inStock: true,
    quantity: 26,
  },
  {
    name: 'Blueberry Burst Cupcakes Pack',
    category: 'Cupcakes',
    price: 329,
    image: 'https://via.placeholder.com/300x300?text=Blueberry+Burst+Cupcakes',
    description: 'Pack of fluffy blueberry cupcakes with lemon cream',
    rating: 4.7,
    inStock: true,
    quantity: 40,
  },
  {
    name: 'Chocolate Ganache Cupcakes Pack',
    category: 'Cupcakes',
    price: 349,
    image: 'https://via.placeholder.com/300x300?text=Ganache+Cupcakes',
    description: 'Deep cocoa cupcakes topped with glossy ganache',
    rating: 4.8,
    inStock: true,
    quantity: 38,
  },
  {
    name: 'Mini Hazelnut Bliss Cake',
    category: 'Mini Cakes',
    price: 219,
    image: 'https://via.placeholder.com/300x300?text=Mini+Hazelnut+Bliss',
    description: 'Single serve mini cake with hazelnut praline cream',
    rating: 4.8,
    inStock: true,
    quantity: 48,
  },
  {
    name: 'Mini Strawberry Cream Cake',
    category: 'Mini Cakes',
    price: 209,
    image: 'https://via.placeholder.com/300x300?text=Mini+Strawberry+Cream',
    description: 'Soft mini sponge layered with fresh strawberry cream',
    rating: 4.7,
    inStock: true,
    quantity: 46,
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    const products = await Product.insertMany(seedData);
    console.log(`Inserted ${products.length} products`);

    await mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedProducts();
